---
name: competition_tracker
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_bloc: ^5.0.1
  intl: ^0.16.1
  url_launcher: ^5.5.0
  flutter_local_notifications: ^1.4.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/logos/atcoder_logo.png
  - assets/images/logos/codechef_logo.png
  - assets/images/logos/codeforces_logo.jpg
  - assets/images/logos/facebook_hackercup_logo.png
  - assets/images/logos/google_coding_competitions_logo.jpg
  - assets/images/logos/hackerearth_logo.jpeg
  - assets/images/logos/hackerrank_logo.png
  - assets/images/logos/kaggle_logo.png
  - assets/images/logos/leetcode_logo.jpeg
  - assets/images/logos/project_euler_logo.jpeg
  - assets/images/logos/topcoder_logo.jpg
