/// Generated by AssetsRefGenerator on 2020/07/20
class Res {
  static const String codeforces_logo =
      "assets/images/logos/codeforces_logo.jpg";
  static const String google_coding_competitions_logo =
      "assets/images/logos/google_coding_competitions_logo.jpg";
  static const String kaggle_logo = "assets/images/logos/kaggle_logo.png";
  static const String hackerrank_logo =
      "assets/images/logos/hackerrank_logo.png";
  static const String atcoder_logo = "assets/images/logos/atcoder_logo.png";
  static const String codechef_logo = "assets/images/logos/codechef_logo.png";
  static const String project_euler_logo =
      "assets/images/logos/project_euler_logo.jpeg";
  static const String topcoder_logo = "assets/images/logos/topcoder_logo.jpg";
  static const String facebook_hackercup_logo =
      "assets/images/logos/facebook_hackercup_logo.png";
  static const String leetcode_logo = "assets/images/logos/leetcode_logo.jpeg";
  static const String hackerearth_logo =
      "assets/images/logos/hackerearth_logo.jpeg";
}
